-- ============================================================
-- Aggregate Functions with GROUP BY - Smart Clinic Database
-- ============================================================

USE SmartClinic;

-- ============================================================
-- Query 1: Count appointments per doctor
-- Purpose: Analyze workload distribution among doctors
-- ============================================================
SELECT 
    d.doctor_id,
    CONCAT(e.first_name, ' ', e.last_name) AS doctor_name,
    d.specialization,
    COUNT(a.appointment_id) AS total_appointments,
    COUNT(CASE WHEN a.status = 'Completed' THEN 1 END) AS completed_appointments,
    COUNT(CASE WHEN a.status = 'Scheduled' THEN 1 END) AS scheduled_appointments,
    COUNT(CASE WHEN a.status = 'Cancelled' THEN 1 END) AS cancelled_appointments
FROM Doctor d
INNER JOIN Employee e ON d.employee_id = e.employee_id
LEFT JOIN Appointment a ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id, e.first_name, e.last_name, d.specialization
ORDER BY total_appointments DESC;

-- ============================================================
-- Query 2: Calculate total revenue per doctor
-- Purpose: Determine income generated by each doctor
-- ============================================================
SELECT 
    d.doctor_id,
    CONCAT(e.first_name, ' ', e.last_name) AS doctor_name,
    d.specialization,
    COUNT(DISTINCT a.appointment_id) AS total_appointments,
    SUM(t.cost) AS total_treatment_revenue,
    AVG(t.cost) AS average_treatment_cost,
    SUM(py.amount) AS total_payments_received
FROM Doctor d
INNER JOIN Employee e ON d.employee_id = e.employee_id
LEFT JOIN Appointment a ON d.doctor_id = a.doctor_id
LEFT JOIN Appointment_Treatment at ON a.appointment_id = at.appointment_id
LEFT JOIN Treatment t ON at.treatment_id = t.treatment_id
LEFT JOIN Payment py ON a.appointment_id = py.appointment_id
WHERE py.status = 'Paid'
GROUP BY d.doctor_id, e.first_name, e.last_name, d.specialization
ORDER BY total_treatment_revenue DESC;

-- ============================================================
-- Query 3: Analyze patients by gender and age group
-- Purpose: Get demographic distribution of patients
-- ============================================================
SELECT 
    p.gender,
    CASE 
        WHEN YEAR(CURDATE()) - YEAR(p.date_of_birth) < 18 THEN 'Under 18'
        WHEN YEAR(CURDATE()) - YEAR(p.date_of_birth) BETWEEN 18 AND 30 THEN '18-30'
        WHEN YEAR(CURDATE()) - YEAR(p.date_of_birth) BETWEEN 31 AND 50 THEN '31-50'
        ELSE 'Over 50'
    END AS age_group,
    COUNT(p.patient_id) AS patient_count,
    AVG(YEAR(CURDATE()) - YEAR(p.date_of_birth)) AS average_age
FROM Patient p
GROUP BY p.gender, age_group
ORDER BY p.gender, age_group;

-- ============================================================
-- Query 4: Calculate average and total costs by treatment type
-- Purpose: Understand treatment economics
-- ============================================================
SELECT 
    t.treatment_id,
    t.treatment_name,
    COUNT(DISTINCT at.appointment_id) AS times_performed,
    COUNT(DISTINCT a.patient_id) AS unique_patients,
    AVG(t.cost) AS average_cost,
    MIN(t.cost) AS minimum_cost,
    MAX(t.cost) AS maximum_cost,
    SUM(t.cost) AS total_revenue,
    AVG(t.estimated_duration_hours) AS avg_duration_hours
FROM Treatment t
LEFT JOIN Appointment_Treatment at ON t.treatment_id = at.treatment_id
LEFT JOIN Appointment a ON at.appointment_id = a.appointment_id
GROUP BY t.treatment_id, t.treatment_name
ORDER BY total_revenue DESC;

-- ============================================================
-- Query 5: Analyze prescription medicines usage
-- Purpose: Track most frequently prescribed medications
-- ============================================================
SELECT 
    m.medicine_id,
    m.medicine_name,
    m.formula,
    COUNT(pd.prescription_detail_id) AS times_prescribed,
    COUNT(DISTINCT pr.patient_id) AS unique_patients,
    AVG(pd.dosage) AS average_dosage,
    MAX(pd.duration_days) AS max_duration_days,
    MIN(pd.duration_days) AS min_duration_days,
    m.stock_quantity,
    m.price,
    (COUNT(pd.prescription_detail_id) * m.price) AS estimated_revenue
FROM Medicine m
LEFT JOIN Prescription_Detail pd ON m.medicine_id = pd.medicine_id
LEFT JOIN Prescription pr ON pd.prescription_id = pr.prescription_id
GROUP BY m.medicine_id, m.medicine_name, m.formula, m.stock_quantity, m.price
HAVING COUNT(pd.prescription_detail_id) > 0
ORDER BY times_prescribed DESC;

-- ============================================================
-- Query 6: Monthly appointment statistics
-- Purpose: Track clinic activity trends by month
-- ============================================================
SELECT 
    YEAR(a.appointment_date) AS year,
    MONTH(a.appointment_date) AS month,
    MONTHNAME(a.appointment_date) AS month_name,
    COUNT(a.appointment_id) AS total_appointments,
    COUNT(CASE WHEN a.status = 'Completed' THEN 1 END) AS completed,
    COUNT(CASE WHEN a.status = 'Cancelled' THEN 1 END) AS cancelled,
    COUNT(CASE WHEN a.status = 'No-Show' THEN 1 END) AS no_show,
    COUNT(DISTINCT a.patient_id) AS unique_patients,
    COUNT(DISTINCT a.doctor_id) AS doctors_involved,
    AVG(DATEDIFF(a.appointment_date, CURDATE())) AS days_ahead_scheduled
FROM Appointment a
GROUP BY YEAR(a.appointment_date), MONTH(a.appointment_date), 
         MONTHNAME(a.appointment_date)
ORDER BY year DESC, month DESC;

-- ============================================================
-- Query 7: Payment analysis by method and status
-- Purpose: Understand payment collection performance
-- ============================================================
SELECT 
    py.payment_method,
    py.status,
    COUNT(py.payment_id) AS payment_count,
    SUM(py.amount) AS total_amount,
    AVG(py.amount) AS average_amount,
    MIN(py.amount) AS minimum_amount,
    MAX(py.amount) AS maximum_amount,
    ROUND((COUNT(py.payment_id) / (SELECT COUNT(*) FROM Payment)) * 100, 2) AS percentage_of_total
FROM Payment py
GROUP BY py.payment_method, py.status
ORDER BY total_amount DESC;

-- ============================================================
-- Query 8: Employee salary statistics by role
-- Purpose: Analyze compensation across staff positions
-- ============================================================
SELECT 
    e.employee_type,
    COUNT(e.employee_id) AS total_employees,
    AVG(e.salary) AS average_salary,
    MIN(e.salary) AS minimum_salary,
    MAX(e.salary) AS maximum_salary,
    SUM(e.salary) AS total_payroll,
    STDDEV(e.salary) AS salary_stddev
FROM Employee e
GROUP BY e.employee_type
ORDER BY average_salary DESC;

-- ============================================================
-- Query 9: Patient appointment frequency analysis
-- Purpose: Identify patient engagement patterns
-- ============================================================
SELECT 
    CASE 
        WHEN appointment_count = 0 THEN 'No Appointments'
        WHEN appointment_count = 1 THEN '1 Appointment'
        WHEN appointment_count BETWEEN 2 AND 5 THEN '2-5 Appointments'
        WHEN appointment_count BETWEEN 6 AND 10 THEN '6-10 Appointments'
        ELSE '10+ Appointments'
    END AS appointment_frequency,
    COUNT(DISTINCT patient_id) AS patient_count,
    AVG(appointment_count) AS average_appointments_per_patient,
    MIN(appointment_count) AS minimum_appointments,
    MAX(appointment_count) AS maximum_appointments
FROM (
    SELECT 
        p.patient_id,
        COUNT(a.appointment_id) AS appointment_count
    FROM Patient p
    LEFT JOIN Appointment a ON p.patient_id = a.patient_id
    GROUP BY p.patient_id
) AS patient_stats
GROUP BY appointment_frequency
ORDER BY patient_count DESC;

-- ============================================================
-- Query 10: Treatment specialization by doctor
-- Purpose: Analyze doctor expertise in specific treatments
-- ============================================================
SELECT 
    d.doctor_id,
    CONCAT(e.first_name, ' ', e.last_name) AS doctor_name,
    d.specialization,
    t.treatment_name,
    COUNT(DISTINCT at.appointment_id) AS treatments_performed,
    COUNT(DISTINCT a.patient_id) AS patients_treated,
    SUM(t.cost) AS total_treatment_revenue,
    AVG(t.cost) AS average_treatment_cost
FROM Doctor d
INNER JOIN Employee e ON d.employee_id = e.employee_id
INNER JOIN Appointment a ON d.doctor_id = a.doctor_id
INNER JOIN Appointment_Treatment at ON a.appointment_id = at.appointment_id
INNER JOIN Treatment t ON at.treatment_id = t.treatment_id
GROUP BY d.doctor_id, e.first_name, e.last_name, d.specialization, 
         t.treatment_id, t.treatment_name
ORDER BY d.doctor_id, total_treatment_revenue DESC;

-- ============================================================
-- Query 11: Medicine inventory value analysis
-- Purpose: Determine inventory value and turnover
-- ============================================================
SELECT 
    'Medicine Inventory Summary' AS report_type,
    COUNT(DISTINCT m.medicine_id) AS total_medicines,
    SUM(m.stock_quantity) AS total_units_in_stock,
    SUM(m.stock_quantity * m.price) AS total_inventory_value,
    AVG(m.stock_quantity) AS average_stock_per_medicine,
    AVG(m.price) AS average_price_per_medicine,
    MIN(m.price) AS lowest_price,
    MAX(m.price) AS highest_price
FROM Medicine m;

-- ============================================================
-- Query 12: Appointment cancellation rate analysis
-- Purpose: Understand cancellation patterns
-- ============================================================
SELECT 
    d.specialization,
    COUNT(a.appointment_id) AS total_appointments,
    COUNT(CASE WHEN a.status = 'Cancelled' THEN 1 END) AS cancelled_count,
    COUNT(CASE WHEN a.status = 'No-Show' THEN 1 END) AS no_show_count,
    ROUND((COUNT(CASE WHEN a.status = 'Cancelled' THEN 1 END) / 
            COUNT(a.appointment_id)) * 100, 2) AS cancellation_rate,
    ROUND((COUNT(CASE WHEN a.status = 'No-Show' THEN 1 END) / 
            COUNT(a.appointment_id)) * 100, 2) AS no_show_rate
FROM Doctor d
LEFT JOIN Appointment a ON d.doctor_id = a.doctor_id
GROUP BY d.specialization
ORDER BY cancellation_rate DESC;
